name: mononz
description: Android App Developer, NodeJS Enthusiast, Electronics Engineer
meta_description: "Android App Developer, NodeJS Enthusiast, Electronics Engineer"
cover: https://static.mononz.net/ghost/robotic.jpg

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://mononz.net'
google_analytics: 'UA-66651130-6'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://mononz.net/'
author:         'Jared Hall'
